### ISSUE TITLE
Guaranteed minimum higher than any point on average line

### ISSUE THREAD

**Issue by Kemp-J** [elxris/Turnip-Calculator#102]
Screenshot below. Is this expected or a bug? The guaranteed minimum is higher than any point on the average line, which doesn't make any sense to me.

![Screenshot_20200427-093813_Chrome](https://user-images.githubusercontent.com/9304056/80352027-2e6d1380-886b-11ea-9a20-6110fab82d7a.jpg)

**Comment by jeffgillean** [comment]
This makes sense because the lines fluctuate independently. Different patterns peak at different times, so even though the _average_ value never goes that high, each individual line is guaranteed to peak _at least_ as high as the guaranteed minimum.

This is an overly simple example, but imagine there are only two possible lines: one starts at 100 bells and smoothly decreases to 0 bells; the other starts at 0 bells and smoothly increases to 100 bells. The average is 50 bells every single day, but your guaranteed minimum is 100 because both lines are guaranteed to reach 100 bells _at least once_ (in this case _exactly_ once) before the end of the week.
