### ISSUE TITLE
[BUG] Mobile seems to break the graph

### ISSUE THREAD

**Issue by g2bb** [elxris/Turnip-Calculator#105]
**Version of the tool**
1.9.1

**Describe the bug**
Opening the site on my phone seems to completely break the graph in ways I can't describe, so here's an image
![Screenshot_20200427-231114](https://user-images.githubusercontent.com/15370969/80446620-ebe41f00-88dc-11ea-84e1-3860a5d52d54.jpg)

**To Reproduce**
open in mobile browser

**Expected behavior**
graph should predict the process for the week

**Smartphone (please complete the following information):**
 - Device: OnePlus 6T McLaren Edition
 - OS: Android 10
 - Browser Brave and Crome
 - Version 1.5.131(brave) and 81.0.4044.117 (chrome)

**Additional context**
Added app to my home screen via built in feature in browser. Still happens when I open it as a normal tab

**Comment by devvoid** [comment]
Not just on mobile - I'm having the same issue on desktop.

OS: Ubuntu 19.10
Browser: Firefox 75.0

Just yesterday everything was working just fine.

**Comment by g2bb** [comment]
Since @devvoid is having issues on a distro Linux I'm wondering if it's a Linux issue since Android is built on Linux

**Comment by g2bb** [comment]
NVM I'm getting it on my laptop now too

**Comment by DaniTheLegend** [comment]
Samsung galaxy s9 stopped working this monday. Best of luck with this bug!

**Comment by elxris** [comment]
> Opening the site on my phone seems to completely break the graph in ways I can't describe, so here's an image

I don't see the error. Please try to describe the error.

**Comment by g2bb** [comment]
> > Opening the site on my phone seems to completely break the graph in ways I can't describe, so here's an image
> 
> I don't see the error. Please try to describe the error.

Like I said I can't describe it... Best I can do is that it bumps up and down. I included an image in the original post, lmk if you can't see that image

**Comment by elxris** [comment]
> > > Opening the site on my phone seems to completely break the graph in ways I can't describe, so here's an image
> > 
> > 
> > I don't see the error. Please try to describe the error.
> 
> Like I said I can't describe it... Best I can do is that it bumps up and down. I included an image in the original post, lmk if you can't see that image

I can see the image. Those bumps are intended, and they are the underlying patterns of the result. This weird coloring is to give more sense of the probabilities that could occur.

I realize now that this kind of visualization is not the best for our purpose. I will try to explore more kinds of visualization.

We have a violin visualization proposal in #101, but, if you feel that violin plots are not the best for the calculator purpose, you could propose a new one.

**Comment by DaniTheLegend** [comment]
For me whenever I was inputing the turnip prices it didnt change the curve
or the pattern inside the curve at all

**Comment by vythefirst** [comment]
![image](https://user-images.githubusercontent.com/64921089/81210450-c1523000-8f86-11ea-9ad6-2528cba71700.png)
![image](https://user-images.githubusercontent.com/64921089/81210477-c7e0a780-8f86-11ea-8d1a-e8c6976c41af.png)

I think I was experiencing the same bug. Last night I was logging in and I wanted to see how the graph worked, so I put in all kinds of numbers into the Wed Morning spot but it generally didn't change except for the # of peaks between 3-4. I couldn't understand what pattern was happening, so I just assumed that it needed more information to find a pattern.

Today I opened the same link and the graph looked like the 2nd picture. Logging in my Wed Morning amount (159) didn't do anything to the graph and just fell within parameters. I reset and re-entered my values not including Wednesday Morning and it still looks like this. I'm a little upset that I didn't see this prediction yesterday, otherwise I would have sold my turnips haha ; ; ; ; It didn't occur to me that it could be a bug until I saw everyone else having these issues as well!

**Comment by elxris** [comment]
The second graph is the right one. I have been fixing #113 and #95. I am confident this more accurate. I am sorry about the inconvenience.

I am closing this ticket to move forward to 2.0.1-build.18

If you still have a problem, please rise another ticket.
