### ISSUE TITLE
[BUG] Inaccurate early reporting, switched 100% conclusion Tursday PM

### ISSUE THREAD

**Issue by KrisRuleZ** [elxris/Turnip-Calculator#133]
**Version of the tool**
v2.1.2-build.3

**Describe the bug**
Entered in all prices accurate to my game. 
Had a 100% confirmation of "Small Spike" appearing around Saturday AM 
Put in Thursday PM prices, switched to 100% confirmation of "decreasing" 

**To Reproduce**
Buy Price: 101 
Mon AM: 93 
Mon PM: 91 
Tue AM: 85
Tue PM: 80
Wed AM: 76
Wed PM: 72
Thu AM 68 
(All of these entries will confirm 100% Small spike with a Guaranteed min of 153) 
Thu PM: 63
(Now switches to 100% confirmed decreasing)

**Expected behavior**
I expected the 100% confirmation to be accurate and not switch Thursday PM

**Screenshots**
![image](https://user-images.githubusercontent.com/66438837/83797804-69c7e280-a660-11ea-931c-b2917aba6c37.png)

![image](https://user-images.githubusercontent.com/66438837/83797833-75b3a480-a660-11ea-9bc4-14e135d80920.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version ??

**Additional context**
Not so much of a technical issue as it is a programming issue.

**Comment by elxris** [comment]
Thanks a lot for opening a new issue!

This tool uses **Ninji's extracted code** of the game.
So, everything we know, and hence, what the calculator knows, is confined to this code.

If we look at the [game's code](https://gist.github.com/Treeki/85be14d297c80c8b3c0a76375743325b#file-turnipprices-cpp-L302-L311) responsible for decreasing pattern:

We will see that the first value (Monday AM) is `intceil(rate * baseprice)`
Monday AM should have a rate of a minimum of 0.85 and a maximum of 0.9.
If your base price is 110 so the minimum that Monday AM should reach is 93.5, but we need to ceil that value. So it's 94. So, your recorded value is off the charts. Given what we know.

I don't want to say that you recorded this value wrong, but I can't prove that your Mon AM value matches this pattern.

This inaccurate early reporting is because we try to exact match every pattern, if later we find out that we don't have a 100% match pattern we will activate a _heuristic filter_ to try to give you the best match pattern.

I hope this answer can help you. We try to give the best predictions if the numbers match the known algorithm.

**Comment by KrisRuleZ** [comment]
Your conclusion that I entered my first number incorrectly is probably most accurate, because on Monday AM it was actually also 91, but I made it 93 because I didn't think 91 made sense. But I was unaware that there were AM and PM prices until i found this site monday morning, so I'm not sure why I got the same number for Monday AM/PM and why I was so certain that was correct, but oh well. Thank you for your response, off to beg my friends to let me sell on their islands

**Comment by elxris** [comment]
What I was saying is that given you had 110 base price, your Monday AM should be in the range of 94-99 for a decreasing pattern. Maybe it was a bit higher than 91 on Monday? Anyway, I will close this as I think we’re accurately predicting patterns given Ninji’s code.
