### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by jans0225** [elxris/Turnip-Calculator#141]
**Version of the tool**
v2.1.2-build.20

**Describe the bug**
Im not sure if this is a bug but there have been 2 occasions in the last month or so where Im predicted for a spike and by Friday morning, the whole chart flips on me.  I thought the first time it happened it might have been bad data but I'm 100% confident I had the right data in this time and the curve kept narrowing until Friday.  

Is this something that falls in the possibilities of this graph?  Has anyone else brought this up before?

**To Reproduce**

Im missing one time but if you input this data, it will show a large bell curve before flipping on Friday (I cleared my data from the website so just going off text messages here).   

Buy price 109
Mon AM - 96 
PM - 91
Tues AM - 86
PM - forgot this one
Wed AM - 83
PM - 73

**Expected behavior**
Shouldn't this have predicted the down trend earlier?

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome (tested in FF too)
 - Version whatever the most current is as of 6/22/20

**Additional context**
I did have complete data through Friday when the curve flipped.  I thought I had a full price listed in my text messages but didn't.  I cleared last weeks for this weeks data already.

**Comment by elxris** [comment]
Hi Jans, thank you for raising your question.

I think the chart is right, but it fails to communicate that you will probably have decreasing pattern.

This is where the table comes in handy
![image](https://user-images.githubusercontent.com/1855014/85346433-f248de80-b4ba-11ea-805f-6ac5fae28541.png)

Here you can see that with your input data, you could have a decreasing pattern with a 22% probability. A small spike is also probable, with 38%. And finally, what everybody wants, high spike, with 40%. The graph will show all scenarios. That's maybe why it's so hard to tell.

But, a decreasing pattern probability was there since the beginning. It didn't come out of the blue.
