### ISSUE TITLE
[BUG] Forecast eliminates High Spike incorrectly

### ISSUE THREAD

**Issue by thoolihan** [elxris/Turnip-Calculator#151]
**Version of the tool**
v2.1.2-build.28

**Describe the bug**
The forecast tool eliminated the correct option based on real game input, and only corrected on large spike, see screenshots for progression of week and forecasts. Note that I did miss a period of capturing price "Wed AM", but the issue occurred even before then 

**To Reproduce**
See screenshots

**Expected behavior**
I could see a higher probability for other patterns, but it should not have eliminated High Spike

**Screenshots**

This is from actual game data, week of 8/15. Game version 1.4.1

After Monday morning, it's already eliminated High Spike:
<img width="729" alt="Start" src="https://user-images.githubusercontent.com/170989/90313670-5a74d900-dedc-11ea-86a5-5db1d247fde5.png">

By this point, it has eliminated everything but fluctuating:
<img width="727" alt="Middle" src="https://user-images.githubusercontent.com/170989/90313679-5fd22380-dedc-11ea-987f-444940b240ba.png">

Here is where the week ended up:
<img width="734" alt="End" src="https://user-images.githubusercontent.com/170989/90313683-62cd1400-dedc-11ea-8811-da66e5db7e9d.png">

**Desktop (please complete the following information):**
 - OS: Win 10 Home
 - Browser Firefox
 - Version 79.0

**Additional context**

**Comment by elxris** [comment]
From what I see, I believe that the main culprit is your buy price, which should match your island price. Sometimes we put the value of other islands.

If we put 94 as buy price, the maximum sell price for Monday AM is 85, which is much lower than 89. This is not a precision issue. 

I will close this issue because we don't have enough information proving that this is an actual error, but please if you see this again, feel free to open a new issue.
