### ISSUE TITLE
I think rounding math might lead to incorrect results

### ISSUE THREAD

**Issue by droqen** [elxris/Turnip-Calculator#3]
I don't yet have in-game experimental evidence to back this claim up, but I've been thinking a lot about the way prices are calculated (from @_Ninji's work):

intceil(rate * basePrice)

If my basePrice is 105 and the rate variable is something like 89.9%, ceil() will give me a resulting price of 95. The rate variable is within the 85-90% range for Monday AM meaning Pattern 1 is possible, but your tool disqualifies it -- I assume because 95 / 105 is greater than 90%, as a case like 94 / 105 functions properly.

**Comment by elxris** [comment]
Yes, rounding is not the biggest issue with this calculator.

Every number operation in javascript is performed in 64-bit floats.

But Ninji's code performs all operations in 32-bit floats. So the precision is a bit different because of how floating-point operations work.

I aimed for simplicity and added one point to the max values and subtracted one point to min values. This doesn't mean that every max and min is off by one value compared to the game prices, sometimes it is right but sometimes is a bit off.

In any case, I think this tool should focus on pattern recognition rather than very precise predictions. One bell off is not a big deal in my opinion.

Eager to hear your thoughts!

**Comment by droqen** [comment]
I think I see what you've done! I am not worried about the precision of a prediction, but the difference of one bell can make a big difference when it comes to accurate pattern prediction.

For example an initial setup of "Buy $105" and "Mon AM $96" should not be allowed to predict Big Spike prices, as that is a predictive error of hundreds of bells. It won't come up very often, but when it does it's a large margin of error.

**Comment by elxris** [comment]
I think we could calculate the same patterns I'm calculating in C++ to be close to float arithmetics of Ninji's code and then import that file in something like JSON. And only let js do the filtering.

I would need help with this!

**Comment by Vankog** [comment]
Today the Calc broke 💔 for me, too. (screen from Mike Bryant's version, because data fits on one screen ^^ https://github.com/mikebryant/ac-nh-turnip-prices/issues/40)
No first timer. :-) 
![Screenshot_20200410-102406](https://user-images.githubusercontent.com/3804909/78976340-40824e80-7b16-11ea-9bc9-14ed85ccea5e.png)

**Comment by droqen** [comment]
> I think we could calculate the same patterns I'm calculating in C++ to be close to float arithmetics of Ninji's code and then import that file in something like JSON. And only let js do the filtering.
> 
> I would need help with this!

This makes a lot of sense. I've been poking through your code and I think the way you're doing things is very smart. I do not know C++ very well at all or I'd give this a shot. (I might try anyway.) But if anyone is available to port your code over to C++ and just output a file, I'm curious how big it could possibly get to just provide a dataset of all possible turnip prices & their probabilities

**Comment by elxris** [comment]
@droqen Now I am thinking things very different, go check out #14. This forced me to still do calculations on the browser.

**Comment by elxris** [comment]
@Vankog Fortunately I'm doing changes to the pattern solver. (Still work in progress)
But seem to work on your data!
![image](https://user-images.githubusercontent.com/1855014/79002235-a4584780-7b15-11ea-9644-82f3481d6f61.png)

**Comment by mtaylor76** [comment]
Closing for now, seems like the issue was solved.
