### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by fluffy-critter** [elxris/Turnip-Calculator#65]
When I go to the github.io link, I get redirected to ac-turnip.com, which produces a 404 error. Was some site configuration not updated?

**Comment by mtaylor76** [comment]
The ac-turnip.com domain is currently not in use, because people reported their locally-stored price data not transferring between domains, so we're sticking with the github.io domain for now. 

However, if you visited the github.io domain during that time when we were redirecting to ac-turnip.com, your browser probably cached the redirect. Make sure to clear your cache and then try accessing https://elxris.github.io/Turnip-Calculator/ again.

**Comment by fluffy-critter** [comment]
Ah, thanks. I actually only noticed the redirect this morning so I thought that was a new configuration. Any chance the domain could be set to redirect back to the github.io page?

**Comment by mtaylor76** [comment]
It was set to do that at first, but then we ended up in a circular redirect situation with ac-turnip redirecting to the github.io page, but the cached github.io redirect taking people back to ac-turnip.

It's a bit of a tricky situation for now, but once we work out storage that persists between sites, we'll make the switch (either that, or we'll switch on a Sunday when most peoples' prices will be refreshed anyways.)

**Comment by srir** [comment]
I've cleared cache and am still getting redirected to `ac-turnip.com`; is there something else I need to do? This also seems to happen on machines and browsers that I've never used to visit the site before.

**Comment by leoleoasd** [comment]
Also getting redirected to ac-turnip.com.

**Comment by howar31** [comment]
still getting redirected to ac-turnip.com and that site looks like it's not ready yet
