### ISSUE TITLE
WASM support

### ISSUE THREAD

**Issue by thgaskell** [elxris/Turnip-Calculator#7]
In your Reddit post you mentioned wanting to port the original code to WASM?

I spent an evening trying to port the original program to run in the browser (I haven't done this before), but had trouble exposing the functions to the JavaScript runtime. I want to spend a couple more nights this week trying to figure it out 🛠

Are you open to pull requests? I really love the graphs!

**Comment by elxris** [comment]
Yeah, WASM is a side project that could be integrated into the graph.

The graph for its calculations currently uses the code inside src/v2/optimizer.js
But, the code for my experiment is still in src/v2/calculator.js
I may add some comments and a bit of documentation to it later on.

But I wanted to run each one of the 4,294,967,295 possibilities to generate a "real data" graph.

I gave up the experiment because it's not really that useful. And for the use of the calculator, it is good enough as it is.

If you want to try wasm this guy used rust: https://github.com/chengluyu/turnip-price

**Comment by elxris** [comment]
Delivered! #109
