### ISSUE TITLE
Urgent! Local storage data lost because of redirect

### ISSUE THREAD

**Issue by makitsune** [elxris/Turnip-Calculator#93]
I'm using your awesome turnip calculator all the time and as usual, I visited:
https://elxris.github.io/Turnip-Calculator
But I was redirected to:
https://ac-turnip.com
because `location: https://ac-turnip.com` is present in the github.io link

Is it possible to make a small html page that will take the turnip values from localStorage and redirect the user through JavaScript to the new site with
https://ac-turnip.com/share?f=[old-data]

**Comment by elxris** [comment]
Oh, unfortunately, this would be super hard to do. Because I don't have control of elxris.github.io anymore, I mean, the content of ac-turnip.com is the same of elxris.github.io, and GitHub makes the redirection. If you used elxris.github.io till now then you used a cached version. I am so deeply sorry all the domain manage without proper care. I am new to this part of GitHub pages and it was a disaster. I will manage this properly in the future.

**Comment by makitsune** [comment]
Okay, I understand. I wrote a small Node.js script that migrates it over!

In `chrome://version`
<img height="20" src="https://user-images.githubusercontent.com/8362329/79928209-3297cc00-843a-11ea-91d6-7a6b164eaac9.png"/>

```bash
cd /home/maki/.config/google-chrome-unstable/Default/Local\ Storage
npm i level
```
```js
const level = require("level");
const db = level("leveldb");

db.createKeyStream().on("data", key => {
	if (key != "_https://elxris.github.io\u0000\u0001filters") return;
	console.log(JSON.stringify(key));
	db.get(key, (err, value) => {
		if (err) return console.log(err);
		console.log(value);
		db.put("_https://ac-turnip.com\u0000\u0001filters", value, err => {
			if (err) return console.log(err);
			console.log("Written to new site");
		});
	});
});
```
Thank you again for working on your awesome calculator!
